"""add book category

Revision ID: 311170d4e492
Revises: dcc23d1fc7da
Create Date: 2025-11-27 12:57:01.144471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311170d4e492'
down_revision: Union[str, Sequence[str], None] = 'dcc23d1fc7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=13), nullable=False))
    op.add_column('books', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('cover_image_s3_key', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.create_foreign_key(None, 'books', 'book_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'category_id')
    op.drop_column('books', 'publication_year')
    op.drop_column('books', 'cover_image_s3_key')
    op.drop_column('books', 'cover_image_url')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
