"""one-to-one relationship for user reviewing a book

Revision ID: d90583282c40
Revises: ef7a6b3b9a11
Create Date: 2025-12-02 21:23:49.690664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90583282c40'
down_revision: Union[str, Sequence[str], None] = 'ef7a6b3b9a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_book_review_uc', 'reviews', ['book_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_book_review_uc', 'reviews', type_='unique')
    # ### end Alembic commands ###
