"""book category id field as nullable

Revision ID: ef7a6b3b9a11
Revises: 311170d4e492
Create Date: 2025-11-27 14:01:56.227974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7a6b3b9a11'
down_revision: Union[str, Sequence[str], None] = '311170d4e492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('books_category_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'book_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_category_id_fkey'), 'books', 'book_categories', ['category_id'], ['id'])
    op.alter_column('books', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
